engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "nanofeed.js"
exclude_paths:
- "spec/test"
- "**/*.min.js"
- "!**.js"
- "!**.conf.js"