---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - "src/*.js"
  - "spec/*.js"
exclude_paths:
- spec/support/**/*
- "**/*.min.js"
