---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
ratings:
  paths:
  - src/*.js
exclude_paths:
- ./*.js
- spec/*.js
- dist/*.js
